CREATE DATABASE PROYECTO;
USE PROYECTO;
CREATE SCHEMA ACCESO;

CREATE TABLE ACCESO.USUARIO
(
	CÓDIGO SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USUARIO VARCHAR(32) NOT NULL UNIQUE,
	CONTRASEÑA BINARY(64) NOT NULL,
	NOMBRES VARCHAR(64) NOT NULL,
	APELLIDOS VARCHAR(64) NOT NULL
);
CREATE TABLE ACCESO.SESIÓN
(
	CÓDIGO BINARY(64) PRIMARY KEY,
	CÓD_USUARIO SMALLINT UNSIGNED NOT NULL REFERENCES ACCESO.USUARIO,
	EXPIRACIÓN DATETIME NOT NULL
);
CREATE SCHEMA ORGANIZACIÓN;
CREATE TABLE ORGANIZACIÓN.PEI
(
	CÓDIGO TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(64) NOT NULL
);
CREATE TABLE ORGANIZACIÓN.UNIDADORGÁNICA
(
	CÓDIGO TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(64) NOT NULL
);